# Generated by Django 5.2.7 on 2025-11-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending_requirements', 'Pending requirements'), ('requirements_analysis', 'Requirements analysis'), ('drawings_wip', 'Drawings WIP'), ('pending_client_approval', 'Pending client approval'), ('approved_pending_fabrication', 'Approved pending fabrication'), ('in_fabrication', 'In fabrication'), ('in_quality_control', 'In quality control'), ('ready_to_be_shipped', 'Ready to be shipped'), ('shipped', 'Shipped'), ('completed', 'Completed')], default='pending_requirements', max_length=40),
        ),
    ]
